# Make file for OOProgramming Exercises
# Pietro Chimenti 22/08/2016

default: all

all: Ch02 Ch03 Ch04 Ch05

Ch02: 
	cd Ch02 && $(MAKE) 
	cd ..

Ch03:
	cd Ch03 && $(MAKE)
	cd ..

Ch04:
	cd Ch04 && $(MAKE)
	cd ..

Ch05:
	cd Ch05 && $(MAKE)
	cd ..

clean:
	cd Ch02 && $(MAKE) clean
	cd Ch03 && $(MAKE) clean
	cd Ch04 && $(MAKE) clean
	cd Ch05 && $(MAKE) clean
	cd ..

.PHONY: Ch02 Ch03 Ch04 Ch05 clean
